[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://suitmedia-backend.suitdev.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/storage/*"
  to = "https://assets.suitdev.com/storage/:splat"
  status = 200
  force = true
